title: Hello, world! I'm Alli Colyer
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alli Colyer # add your name
author-img: profile.jpeg # add your photo
about-author: I am a technical curriculum developer with a background in chemical engineering. My passion is to make science accessible for people of all ages. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: Allicolyer # add your Github handle
linkedin: allison-colyer # add your Linkedin handle
email: allicolyer@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
